# Generated by Django 2.2.19 on 2021-03-02 09:53

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compnay_name', models.CharField(max_length=100)),
                ('company_website', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_city', models.CharField(max_length=100, unique=True, verbose_name='Police Status')),
                ('address', models.TextField(max_length=200)),
                ('no_of_employee', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('station_incharge', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='Station In Charge')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('model_no', models.CharField(max_length=50)),
                ('manufacute_year', models.CharField(max_length=100, unique=True)),
                ('registered_address', models.CharField(blank=True, max_length=200, null=True)),
                ('registered_district', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_state', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('rc_img', models.FileField(blank=True, null=True, upload_to=application.models.ContentFileName('rc'), verbose_name='RC (Images/PDF)')),
                ('insurance_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('insurance_img', models.FileField(blank=True, null=True, upload_to=application.models.ContentFileName('insurance'), verbose_name='Insurance (Images/PDF)')),
                ('insurance_date', models.DateField(blank=True, null=True, verbose_name='Insurance Validity')),
                ('pollution_img', models.FileField(blank=True, null=True, upload_to=application.models.ContentFileName('pollution'), verbose_name='Pollution (Images/PDF)')),
                ('pollution_date', models.DateField(blank=True, null=True, verbose_name='Pollution Validity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('drivers_licence_no', models.CharField(blank=True, max_length=100, null=True)),
                ('licence_valid_date', models.DateField(blank=True, max_length=100, null=True)),
                ('licence_issue_state', models.CharField(blank=True, max_length=100, null=True)),
                ('licence_img', models.FileField(blank=True, null=True, upload_to=application.models.ContentFileName('licence'), verbose_name='Driver Licence (Images/PDF)')),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.PoliceStation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-user__date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('FIR', 'FIR'), ('Challan', 'Challan'), ('Other', 'Other')], max_length=50)),
                ('complaint', models.TextField(max_length=500)),
                ('challan_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Reject', 'Reject'), ('Paid', 'Paid'), ('Due', 'Due')], default='Pending', max_length=20)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_message', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.PoliceStation', verbose_name='Police Sttion')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pemployee', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
