# Generated by Django 2.2.19 on 2021-03-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='compnay_name',
            new_name='company_name',
        ),
    ]
